export const SELECT_LEVEL = "SELECT_LEVEL";
export const SELECT_KIIP_LEVEL = "SELECT_KIIP_LEVEL";
export const LOGIN_DATA = "LOGIN_DATA";
export const GRAMMAR_UNITS = "GRAMMAR_UNITS";
export const GAME_SCORE = "GAME_SCORE";
export const GAME_DATA = "GAME_DATA";
export const GAME_STATE = "GAME_STATE";
export const DRAG_ANSWER_CHOICE = "DRAG_ANSWER_CHOICE";
export const GAME_ANSWER_NUMBER = "GAME_ANSWER_NUMBER";
//API REQUEST CURRENTLY UNUSED
// export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
// export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
// export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";